### ISSUE TITLE
XHR error (404 Not Found) loading http://localhost:3000/angular2-resizable

### ISSUE THREAD

**Issue by kiranmohanty** [mattlewis92/angular-resizable-element#64]
Hi,
   I would like to use your plugin for resize functionality, but i am facing below error. Could you please help me? 

Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-resizable
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/angular2-resizable as "angular2-resizable" from http://localhost:3000/app/app.module.js

**Comment by mattlewis92** [comment]
Sorry I don't know what's going on from that error, it sounds like an issue with your build configuration. 

p.s. the npm package was renamed to `angular-resizable-element`
